server {
    listen 80;
    server_name 192.168.199.222;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 192.168.199.222;

    ssl_certificate /etc/nginx/ssl/em.crt;
    ssl_certificate_key /etc/nginx/ssl/em.key;

    root /var/www/english-master;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
